name: npm Publish

on:
  release:
    types: [published]

jobs:    
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn run build ngx-masked-input --prod
      - run: yarn publish dist/libs/ngx-masked-input --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn run build ngx-masked-input
      - run: yarn publish dist/libs/ngx-masked-input --prod
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
